name: 573-project
channels:
  - defaults
  - conda-forge
dependencies:
  - scikit-learn
  - intel-openmp=2021.4.0
  - pysocks=1.7.1
  - typing_extensions=4.1.1
  - zlib=1.2.11
  - requests=2.27.1
  - setuptools=61.2.0
  - idna=3.3
  - certifi
  - libffi=3.3
  - six=1.16.0
  - sqlite=3.38.2
  - packaging=21.3
  - transformers
  - openssl
  - zipp=3.7.0
  - wheel=0.37.1
  - filelock=3.6.0
  - importlib-metadata=4.11.3
  - regex=2022.3.15
  - scipy
  - huggingface_hub=0.2.1
  - yaml=0.2.5
  - mkl-service=2.4.0
  - ncurses=6.3
  - tk=8.6.11
  - tzdata=2022a
  - sacremoses=0.0.43
  - mkl=2021.4.0
  - ninja=1.10.2
  - charset-normalizer=2.0.4
  - ca-certificates
  - pyparsing=3.0.4
  - cryptography=36.0.0
  - pycparser=2.21
  - pyyaml=6.0
  - tqdm=4.63.0
  - brotlipy=0.7.0
  - threadpoolctl=2.2.0
  - blas=1.0
  - future=0.18.2
  - joblib=1.1.0
  - pytorch
  - urllib3=1.26.8
  - dataclasses=0.8
  - mkl_fft=1.3.1
  - pyopenssl=22.0.0
  - numpy=1.21.5
  - importlib_metadata=4.11.3
  - readline=8.1.2
  - tokenizers=0.10.3
  - xz=5.2.5
  - typing-extensions=4.1.1
  - click=8.0.4
  - cffi=1.15.0
  - mkl_random=1.2.2
  - colorama=0.4.4
  - numpy-base=1.21.5
  - python=3.9.12
  - pip=21.2.4
  - datasets
  - pandas
  - cudatoolkit=10.2
  - spacy
  - empath
  - nltk
