name: ling573-env
channels:
  - huggingface
  - defaults
dependencies:
  - blas=1.0
  - boto3=1.21.32
  - botocore=1.24.32
  - brotlipy=0.7.0
  - ca-certificates=2022.3.29
  - certifi=2021.10.8
  - cffi=1.15.0
  - charset-normalizer=2.0.4
  - click=8.0.4
  - colorama=0.4.4
  - cryptography=36.0.0
  - dataclasses=0.8
  - filelock=3.6.0
  - future=0.18.2
  - huggingface_hub=0.2.1
  - idna=3.3
  - importlib-metadata=4.11.3
  - importlib_metadata=4.11.3
  - jmespath=0.10.0
  - joblib=1.1.0
  - libcxx=12.0.0
  - libffi=3.3
  - libprotobuf=3.19.1
  - ncurses=6.3
  - ninja=1.10.2
  - nltk=3.7
  - numpy=1.21.5
  - numpy-base=1.21.5
  - openssl=1.1.1n
  - packaging=21.3
  - protobuf=3.19.1
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pyparsing=3.0.4
  - pysocks=1.7.1
  - python=3.9.12
  - python-dateutil=2.8.2
  - pytorch=1.10.2
  - pyyaml=6.0
  - readline=8.1.2
  - regex=2022.3.15
  - requests=2.27.1
  - s3transfer=0.5.0
  - sacremoses=0.0.43
  - scikit-learn=1.0.2
  - sentencepiece=0.1.95
  - setuptools=61.2.0
  - six=1.16.0
  - sqlite=3.38.2
  - tk=8.6.11
  - tokenizers=0.10.3
  - tqdm=4.63.0
  - transformers=4.11.3
  - typing-extensions=4.1.1
  - typing_extensions=4.1.1
  - tzdata=2022a
  - urllib3=1.26.8
  - wheel=0.37.1
  - xz=5.2.5
  - yaml=0.2.5
  - zipp=3.7.0
  - zlib=1.2.11
  - pip=21.2.4
  - pip:
    - mkl==2021.4.0
    - mkl-service==2.4.0
    - mkl_fft==1.3.1
    - mkl_random==1.2.2
    - intel-openmp==2021.4.0
