name: 573-project
channels:
  - defaults
dependencies:
  - jmespath=0.10.0
  - sacremoses=0.0.43
  - botocore=1.24.32
  - click=8.0.4
  - ninja=1.10.2
  - openssl=1.1.1n
  - sqlite=3.38.2
  - importlib_metadata=4.11.3
  - torchtext=0.11.2
  - zipp=3.7.0
  - zlib=1.2.11
  - tqdm=4.63.0
  - xz=5.2.5
  - nltk=3.7
  - transformers=4.11.3
  - regex=2022.3.15
  - requests=2.27.1
  - wheel=0.37.1
  - filelock=3.6.0
  - pyparsing=3.0.4
  - brotlipy=0.7.0
  - typing-extensions=4.1.1
  - pip=21.2.4
  - scikit-learn=1.0.2
  - packaging=21.3
  - pytorch=1.10.2
  - boto3=1.21.32
  - yaml=0.2.5
  - python-dateutil=2.8.2
  - libcxx=12.0.0
  - mkl=2021.4.0
  - pyyaml=6.0
  - typing_extensions=4.1.1
  - python=3.9.12
  - pycparser=2.21
  - ncurses=6.3
  - tokenizers=0.10.3
  - cryptography=36.0.0
  - pyopenssl=22.0.0
  - cffi=1.15.0
  - libgfortran=3.0.1
  - importlib-metadata=4.11.3
  - mkl-service=2.4.0
  - colorama=0.4.4
  - mkl_random=1.2.2
  - scipy=1.7.3
  - sentencepiece=0.1.95
  - numpy=1.21.5
  - tzdata=2022a
  - intel-openmp=2021.4.0
  - pysocks=1.7.1
  - urllib3=1.26.8
  - setuptools=61.2.0
  - numpy-base=1.21.5
  - mkl_fft=1.3.1
  - readline=8.1.2
  - charset-normalizer=2.0.4
  - dataclasses=0.8
  - threadpoolctl=2.2.0
  - tk=8.6.11
  - huggingface_hub=0.2.1
  - libffi=3.3
  - six=1.16.0
  - blas=1.0
  - ca-certificates=2022.3.29
  - llvm-openmp=12.0.0
  - protobuf=3.19.1
  - certifi=2021.10.8
  - future=0.18.2
  - idna=3.3
  - libprotobuf=3.19.1
  - joblib=1.1.0
  - s3transfer=0.5.0
